### ISSUE TITLE
[META] Migrate to v2 Twitter API

### ISSUE THREAD

**Issue by glciampaglia** [CSDL-UMD/Rockwell#7]
~~__NOTE__: this is currently on hold since there are no endpoints to migrate to.~~

Earlier in the year [Twitter announced the new API (v2)](https://blog.twitter.com/developer/en_us/topics/tools/2020/introducing_new_twitter_api.html). The current API (v1.1) will be deprecated soon, so we should make sure all our code is using the new API. 

__Update__: We will migrate to v2. Right now we are using tweepy in three areas:
* [x] #14: Authenticating the user with OAuth workflow (not needed)
* [x] #15: Fetching the tweets with user_timeline endpoint
* [x] #16: Retweet / like tweets on behalf of the user

We will keep this issue as a meta-issue of the other individual tasks.

**Comment by RobertAndion** [comment]
I will have to check on this when I have the chance, however it is probably more relevant to wait for Tweepy to be updated since this is our form of accessing the API. I am hoping they adapt most of the new changes for us to keep things simple.

**Comment by glciampaglia** [comment]
We discussed this issue. We could not find any news about Tweepy updating to v2, and Twitter does not have a definite timeline for when v1.1 will be deprecated. So we decided we will switch to v2 right away to avoid any future problem. 

Right now we are using tweepy in three areas:
1. Authenticating the user with OAuth workflow
2. Fetching the tweets with user_timeline endpoint
3. Retweet / like tweets on behalf of the user

We will keep this issue as a meta-issue of the other individual tasks.

**Comment by glciampaglia** [comment]
We created a new project on the Twitter developer portal to be able to access the v2 api. We decided we will start focusing on #14 first.

**Comment by glciampaglia** [comment]
We applied for the academic track, and were accepted. So this is another incentive to switch to v2, where it makes sense to do so (for example in the case of #17, it seems that v1 is better).

**Comment by saumyabhadani95** [comment]
All the three tasks are done, so closing this issue.
